### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-Cloth-Swap-Workflow\\__init__.py'

### ISSUE THREAD

**Issue by laoliu1023** [REDact324/ComfyUI-Cloth-Swap-Workflow#1]
Cannot import F:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Cloth-Swap-Workflow module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-Cloth-Swap-Workflow\\__init__.py'

**Comment by REDact324** [comment]
Well this is not a costume mode, just a JSON file for workflow. Simply download the JSON file and drag it to the platform of your ComfyUI.
